apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flair-bi.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "flair-bi.name" . }}
    helm.sh/chart: {{ include "flair-bi.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "flair-bi.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "flair-bi.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
{{ toYaml .Values.annotations | indent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: FLAIR_COMPONENT
              value: "flair-bi"
{{- if .Values.env }}
    {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
    {{- end}}
{{- end }}
{{- if .Values.secretEnv.keys }}
    {{- range .Values.secretEnv.keys }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.secretEnv.name }}
                  key: {{ . }}
    {{- end}}
{{- end }}
          ports:
            - name: http
              containerPort: 8002
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /management/health
              port: http
            initialDelaySeconds: 180
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /management/health
              port: http
            initialDelaySeconds: 120
            timeoutSeconds: 5
          resources:
{{ toYaml .Values.resources | indent 12 }}
        {{- if .Values.secretMountName }}
          volumeMounts:
            - name: secrets
              mountPath: "/opt/flair/secrets"
              readOnly: true
        {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- if .Values.secretMountName }}
      volumes:
        - name: secrets
          secret:
            secretName: {{ .Values.secretMountName }}
    {{- end }}
