# Default values for flair-bi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: flairbi/flairbi
  tag: v2.7.6
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

# Secret mount to be used if any secret files are needed to be added to the container during startup
# secretMountName: flair-secret

service:
  type: ClusterIP
  port: 8002

env:
  JHIPSTER_SLEEP: 0
  SPRING_PROFILES_ACTIVE: kube
  CONFIG_URI: http://flair-registry:8761
  EUREKA_URL: http://admin:admin@flair-registry:8761/eureka
  POSTGRES_URI: flair-bi-pg-postgresql:5432
  GRPC_SSL_ENABLED: false

# Can be used if you want to set environment variables from a secret
# The key names need to be the same as the environment variables you want to set
# You would have to make sure the secret is created with the same key names as the environment variables you would like to set

secretEnv:
  name: flair-secret
  keys: []
#     - FLAIR_SECRET_USERNAME
#     - FLAIR_SECRET_PASSWORD

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: false
  path: /*
  gcp:
    certificate:
      create: false
      domain: cloud.devsupport-vizcentric.com
  annotations: {}
    # kubernetes.io/ingress.global-static-ip-name: flair-gcp-static-ip
    # networking.gke.io/managed-certificates: flair-bi

annotations:
  sidecar.istio.io/rewriteAppHTTPProbers: "true"
