# Default values for flair-engine.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: flairbi/flair-engine
  tag: v2.6.6
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

# Secret mount to be used if any secret files are needed to be added to the container during startup
# secretMountName: flair-secret

service:
  type: ClusterIP
  port: 6565

env:
  JHIPSTER_SLEEP: 0
  SPRING_PROFILES_ACTIVE: grpc,kube
  CONFIG_URI: http://flair-registry:8761
  EUREKA_URL: http://admin:admin@flair-registry:8761/eureka
  POSTGRES_URI: flair-engine-pg-postgresql:5432
  GRPC_SSL_ENABLED: false

# Can be used if you want to set environment variables from a secret
# The key names need to be the same as the environment variables you want to set
# You would have to make sure the secret is created with the same key names as the environment variables you would like to set

secretEnv:
  name: flair-secret
  keys: []
#     - FLAIR_SECRET_USERNAME
#     - FLAIR_SECRET_PASSWORD

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

annotations:
  sidecar.istio.io/rewriteAppHTTPProbers: "true"
